/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public String hi() {
        return "Hello test";
    }

    public static void main(String[] args)
    {
        System.out.println(new App().hi());
    }
}
